version: "3.9"

services:
  backend:
    build: ./backend_flask
    env_file:
      - backend_flask/.env
    ports:
      - "5001:5001"
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE=http://localhost:5001
    depends_on:
      - backend
